# Generated by Django 2.0.3 on 2018-08-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_job_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('visibility', models.PositiveIntegerField(choices=[(0, 'NOT IN IMAGE'), (1, 'INVISIBLE'), (2, 'VISIBLE')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='LabeledSkeletonAttributeVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedSkeletonAttributeVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='mode',
            field=models.CharField(default='interpolation', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='interpolate', max_length=32),
        ),
        migrations.CreateModel(
            name='LabeledSkeleton',
            fields=[
                ('skeleton_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Skeleton')),
                ('frame', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Job')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Label')),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.skeleton', models.Model),
        ),
        migrations.CreateModel(
            name='TrackedSkeleton',
            fields=[
                ('skeleton_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Skeleton')),
                ('frame', models.PositiveIntegerField()),
                ('outside', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.ObjectPath')),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.skeleton', models.Model),
        ),
        migrations.AddField(
            model_name='keypoint',
            name='skeleton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Skeleton'),
        ),
        migrations.AddField(
            model_name='trackedskeletonattributeval',
            name='skeleton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.TrackedSkeleton'),
        ),
        migrations.AddField(
            model_name='labeledskeletonattributeval',
            name='skeleton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledSkeleton'),
        ),
    ]
