version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
    volumes:
      - cvat_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0.5-alpine
    restart: always

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:80" #"8080:8080"
    links:
#      - wdb
      - cvat_db
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        TF_ANNOTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "staging"
        WITH_TESTS: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      DJANGO_LOG_SERVER_URL: ""
      ALLOWED_HOSTS: http://visualconstruction.cee.illinois.edu/
#      WDB_SOCKET_SERVER: wdb
#      WDB_NO_BROWSER_AUTO_OPEN: "True"

    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - ./share:/home/django/share
#  wdb:
#    image: kozea/wdb
#    ports:
#        - "1984:1984"

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
